#!/usr/bin/zsh
#--
# ZSH Login Profile
# =============================================================================
#   The contents of this file are only evaluated when `zsh` is invoked as a
# login shell.
# 
#++

# Start the SSH agent.
# From: http://stackoverflow.com/questions/18880024/start-ssh-agent-on-login
SSH_ENV="$HOME/.ssh/env"

function start_agent() {
  /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
  chmod 600 "${SSH_ENV}"
  source "${SSH_ENV}" > /dev/null
  /usr/bin/ssh-add
}

if [[ -f "${SSH_ENV}" ]] ; then
  source "${SSH_ENV}" > /dev/null
  ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
    start_agent
  }
else
  start_agent
fi

# Execute `startx` if we logged into the system from the first virtual
# terminal and the $DISPLAY environment variable has not been set by X.
if [[ -z $DISPLAY ]] && [[ $(tty) == /dev/tty1 ]] ; then
	exec startx
fi

# Export the $DISPLAY environment variable if we're connecting via `tmux` and
# an X session is running.
if [[ -z $DISPLAY && -n "$(pidof X)" && $TERM == 'screen' ]] ; then
  export DISPLAY=:0
fi
