#!/usr/bin/zsh
#--
# ZSH Environment
# =============================================================================
#   This file is evaluated whenever `zsh` is used, regardless of the shell's
# status as a login or interactive shell.
# 
#++

# Assign the appropriate value for $JAVA_HOME if we're running on OS X and
# it has not already been defined.
if [[ $(uname) == 'Darwin' && -z $JAVA_HOME ]] ; then
  export JAVA_HOME=$(/usr/libexec/java_home)
fi

# Path settings. We use $path instead of $PATH here in order to make use of
# the path as an array; combined with `typeset -U`, this ensures that there
# are no duplicate entries in the $PATH.
typeset -U path
path=(
  $HOME/bin
  /usr/local/bin
  $path
)
export PATH

