#!/bin/sh

# Execute default shell scripts when starting X.
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/* ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Update the X resources database.
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# Start background processes.
[ -x $(command -v xcompmgr) ] && xcompmgr &
[ -x $(command -v unclutter) ] && unclutter -idle 1 -root &

# Set the wallpaper.
eval $(cat ~/.fehbg)

# Update the status message for the `dwm` window manager.
while true ; do
	xsetroot -name "$( date '+%e %b %Y | %k:%M' ) | $(whoami)"
	sleep 1s
done &
exec dbus-launch dwm
