#!/bin/sh

# Execute default shell scripts when starting X.
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/* ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Update the X resources database.
xrdb -merge ~/.Xresources

# Start background processes.
xscreensaver -no-splash &

# Set the screen resolution.
xrandr --output default --mode 1280x800

# Update the status message for the `dwm` window manager.
# NOTE: This is done via `xsetroot` in a backgrounded loop.
while true ; do
	xsetroot -name "$( date '+%e %b %Y | %k:%M' ) | $(whoami)"
	sleep 1s
done &

# Launch the window manager.
exec dwm
