autoload -U compinit promptinit
autoload -Uz run-help
compinit
promptinit

setopt AUTO_CD
setopt EXTENDED_GLOB

setopt APPEND_HISTORY SHARE_HISTORY HIST_IGNORE_DUPS HIST_IGNORE_ALL_DUPS
HISTFILE=~/.history
SAVEHIST=10000
HISTSIZE=10000

zstyle ':completion:*' menu select
zstyle ':completion:*' ignore-parents parent pwd

export PATH="$HOME/bin:/usr/local/bin:$PATH"

if [[ -x `which rbenv` ]] ; then
	eval "$(rbenv init -)"
	export PATH="$HOME/.rbenv/bin:$PATH"
fi

if [[ -x `which go` ]] ; then
	export GOPATH="$HOME/Source/Go:$PATH"
fi

PROMPT="%# "
RPROMPT="[%~]"

editors=(vim vi nano)
for editor in $editors ; do
	if [[ -x $(which $editor) ]] ; then
		export EDITOR=$editor
		break
	fi
done

[[ -z $EDITOR ]] && print 'No editor set.'

if [[ $(uname) == 'Darwin' ]] ; then
	for format in mp3 wav aac ogg \
	mp4 m4v mov mpg mpeg avi ogv \
	jpg jpeg png psd bmp gif tif tiff \
	eps ps pdf html dmg ; do
		alias -s $format=open
	done
fi

for format in go md markdown rb rdoc txt text ; do
	alias -s $format=$EDITOR
done

if [[ $(uname) == 'Darwin' || $(uname) == 'FreeBSD' ]] ; then
	export CLICOLOR='yes'
	export LSCOLORS='ExfxcxdxbxEgEdabagacad'
elif [[ -n `ls --color` && $? == 0 ]] ; then
	alias ls='ls --color=auto'
fi

if [[ -x `which bundle` ]] ; then
	alias bex='bundle exec'
fi

if [[ -x `which hub` ]] ; then
	alias git=hub
fi

alias help=run-help
